image: python:3-slim
before_script:
    - pip3 install -r requirements.txt
stages:
    - static_analysis
    - test
static_analysis:
    stage: static_analysis
    script:
        - flake8 src/*.py
app_test:
    stage: test
    script:
          - echo "Tests started..."
          - cd tests
          - python3 -m unittest -v test.py
          - echo "Tests over."


