image: python:3-slim
before_script:
    - pip3 install flake8
    - pip3 install numpy
stages:
    - static_analysis
    - test
static_analysis:
    stage: static_analysis
    script:
        - flake8 --max-line-length=120 src/*.py
app_test:
    stage: test
    script:
          - echo "Tests started..."
          - cd tests
          - python3 test.py
          - echo "Tests over."


